spring:
  application:
    name: logbook-backend


  datasource:
    url: jdbc:h2:mem:logbook
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console.enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect